package data

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/mxygem/greenlight/internal/validator"
	"golang.org/x/crypto/bcrypt"
)

var (
	ErrDuplicateEmail = errors.New("duplicate email")
)

type User struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  password  `json:"-"`
	Activated bool      `json:"activated"`
	Version   int       `json:"-"`
}

type password struct {
	plaintext *string
	hash      []byte
}

func (p *password) Set(plaintextPassword string) error {
	if plaintextPassword == "" {
		return fmt.Errorf("password input required")
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(plaintextPassword), 12)
	if err != nil {
		return fmt.Errorf("generating hash from password: %w", err)
	}

	p.plaintext = &plaintextPassword
	p.hash = hash

	return nil
}

func (p *password) Matches(plaintextPassword string) (bool, error) {
	if plaintextPassword == "" {
		return false, fmt.Errorf("password input required")
	}

	if err := bcrypt.CompareHashAndPassword(p.hash, []byte(plaintextPassword)); err != nil {
		switch {
		case errors.Is(err, bcrypt.ErrMismatchedHashAndPassword):
			return false, nil
		default:
			return false, fmt.Errorf("matching password: %w", err)
		}
	}

	return true, nil
}

func ValidateEmail(v *validator.Validator, email string) {
	v.Check(email != "", "email", "must be provided")
	v.Check(validator.Matches(email, validator.EmailRX), "email", "must be a valid email address")
}

func ValidatePasswordPlaintext(v *validator.Validator, password string) {
	v.Check(password != "", "password", "must be provided")
	v.Check(len(password) >= 8, "password", "must be at least 8 bytes long")
	v.Check(len(password) <= 72, "password", "must not be more than 72 bytes long")
}

func ValidateUser(v *validator.Validator, user *User) {
	v.Check(user.Name != "", "name", "must be provided")
	v.Check(len(user.Name) <= 500, "name", "must not be more than 500 bytes long")

	ValidateEmail(v, user.Email)

	if user.Password.plaintext != nil {
		ValidatePasswordPlaintext(v, *user.Password.plaintext)
	}

	// if password hash is ever nil, this is due to a logic error in our code, likely due to
	// forgetting to set a password for the user. It's a user sanity check to include here, but
	// it's not an issue with the provided user data, so we don't add it to the validation map.
	if user.Password.hash == nil {
		panic("missing password hash for user")
	}
}

type Users interface {
	Insert(user *User) error
	GetByEmail(email string) (*User, error)
	Update(user *User) error
}

// UserModel represents a user in the database and wraps the connection pool.
type UserModel struct {
	DB *sql.DB
}

// Insert adds a new record to the users table. Note: A returning clause is used here due to the
// id, created_at, and version fields are all auto-generated by the db.
func (m UserModel) Insert(user *User) error {
	query := `
		insert into users (name, email, password_hash, activated)
		values ($1, $2, $3, $4)
		returning id, created_at, version`

	args := []any{user.Name, user.Email, user.Password.hash, user.Activated}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	if err := m.DB.QueryRowContext(ctx, query, args...).Scan(&user.ID, &user.CreatedAt, &user.Version); err != nil {
		switch {
		case err.Error() == `pq: duplicate key value violates unique constraint "users_email_key"`:
			return ErrDuplicateEmail
		default:
			return fmt.Errorf("unexpected error inserting user: %w", err)
		}
	}

	return nil
}

// GetByEmail returns zero or one User details if the provided email matches an existing user.
func (m UserModel) GetByEmail(email string) (*User, error) {
	query := `
		select id, created_at, name, email, password_hash, activated, version
		from users
		where email = $1`

	var user User
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	if err := m.DB.QueryRowContext(ctx, query, email).Scan(
		&user.ID,
		&user.CreatedAt,
		&user.Name,
		&user.Email,
		&user.Password.hash,
		&user.Activated,
		&user.Version,
	); err != nil {
		switch {
		case errors.Is(err, sql.ErrNoRows):
			return nil, ErrRecordNotFound
		default:
			return nil, fmt.Errorf("unexpected error looking up user by email: %w", err)
		}
	}

	return &user, nil
}

// Update updates the provided user if found. The user's version number us used to help prevent
// data races.
func (m UserModel) Update(user *User) error {
	query := `
		update users
		set name = $1, email = $2, password_hash = $3, activated = $4, version = version + 1
		where id = $5 and version = %6
		returning version`

	args := []any{
		user.Name,
		user.Email,
		user.Password.hash,
		user.Activated,
		user.ID,
		user.Version,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	if err := m.DB.QueryRowContext(ctx, query, args...).Scan(&user.Version); err != nil {
		switch {
		case err.Error() == `pq: duplicate key value violates unique constraint "users_email_key"`:
			return ErrDuplicateEmail
		case errors.Is(err, sql.ErrNoRows):
			return ErrEditConflict
		default:
			return fmt.Errorf("unexpected error updating user: %w", err)
		}
	}

	return nil
}
